Better detection of apt-get or brew.

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -42,6 +42,17 @@ cosy_prefix=${cosy_prefix:-${cosy_temp}}
 lua_version=${lua_version:-5.2}
 parallel=$(nproc 2> /dev/null || sysctl -n hw.ncpu 2> /dev/null)
 
+{ # Detect if apt-get or brew is available:
+  if command -v apt-get; then
+    if sudo apt-get update; then
+      apt_available=true
+    fi
+  fi >> "${cosy_log}" 2>&1
+  if command -v brew; then
+    brew_available=true
+  fi >> "${cosy_log}" 2>&1
+}
+
 export PATH="${PATH}:/sbin"
 
 # Test if sudo is required:
@@ -114,47 +125,38 @@ cosy_temp=$(realpath "${cosy_temp}")
 # Install dependencies:
 {
   echo -n "Installing development packages... "
-  if command -v apt-get; then
-    if sudo apt-get update; then
-      apt_available=true
-    fi
-  fi >> "${cosy_log}" 2>&1
-  if command -v brew; then
-    brew_available=true
-  fi >> "${cosy_log}" 2>&1
   if [ -z "${apt_available}" ] && [ -z "${brew_available}" ]; then
     echo -e "${green}skipped${nc}"
-    return
+  else
+    case "$(uname -s)" in
+      "Linux")
+        sudo apt-get update  --yes
+        sudo apt-get install --yes make clang gcc diffutils patch curl unzip \
+                                   perl build-essential wget python python-pip \
+                                   libc6-dev libssl-dev \
+                                   libreadline-dev libncurses5-dev libpcre3-dev \
+                                   redis-server imagemagick npm caca-utils libc-bin
+        sudo pip install hererocks
+        ;;
+      "Darwin")
+        HOMEBREW_PREFIX=$(brew config | grep "HOMEBREW_PREFIX" | tr -d ' \t' | cut -d ":" -f 2)
+        export CPATH="${HOMEBREW_PREFIX}/include:${CPATH}"
+        export LIBRARY_PATH="${HOMEBREW_PREFIX}/lib:${LIBRARY_PATH}"
+        export LD_LIBRARY_PATH="${HOMEBREW_PREFIX}/lib:${LD_LIBRARY_PATH}"
+        export DYLD_LIBRARY_PATH="${HOMEBREW_PREFIX}/lib:${DYLD_LIBRARY_PATH}"
+        brew update
+        brew install openssl pcre python redis imagemagick wget npm libcaca
+        brew link --force openssl
+        pip install hererocks
+        ;;
+      *)
+        echo -e "Error: unknown OS: ${red}$(uname -s)${nc}."
+        exit 1
+        ;;
+    esac >> "${cosy_log}" 2>&1 \
+         && echo -e "${green}success${nc}" \
+         || echo -e "${red}failure${nc}"
   fi
-
-  case "$(uname -s)" in
-    "Linux")
-      sudo apt-get update  --yes
-      sudo apt-get install --yes make clang gcc diffutils patch curl unzip \
-                                 perl build-essential wget python python-pip \
-                                 libc6-dev libssl-dev \
-                                 libreadline-dev libncurses5-dev libpcre3-dev \
-                                 redis-server imagemagick npm caca-utils libc-bin
-      sudo pip install hererocks
-      ;;
-    "Darwin")
-      HOMEBREW_PREFIX=$(brew config | grep "HOMEBREW_PREFIX" | tr -d ' \t' | cut -d ":" -f 2)
-      export CPATH="${HOMEBREW_PREFIX}/include:${CPATH}"
-      export LIBRARY_PATH="${HOMEBREW_PREFIX}/lib:${LIBRARY_PATH}"
-      export LD_LIBRARY_PATH="${HOMEBREW_PREFIX}/lib:${LD_LIBRARY_PATH}"
-      export DYLD_LIBRARY_PATH="${HOMEBREW_PREFIX}/lib:${DYLD_LIBRARY_PATH}"
-      brew update
-      brew install openssl pcre python redis imagemagick wget npm libcaca
-      brew link --force openssl
-      pip install hererocks
-      ;;
-    *)
-      echo -e "Error: unknown OS: ${red}$(uname -s)${nc}."
-      exit 1
-      ;;
-  esac >> "${cosy_log}" 2>&1 \
-       && echo -e "${green}success${nc}" \
-       || echo -e "${red}failure${nc}"
   export CPATH="${cosy_prefix}/include:${CPATH}"
   export LIBRARY_PATH="${cosy_prefix}/lib:${LIBRARY_PATH}"
   export LD_LIBRARY_PATH="${cosy_prefix}/lib:${LD_LIBRARY_PATH}"
